### ISSUE TITLE
Convert camelCase functions and variables to snake_case

### ISSUE THREAD

**Issue by aceriverson** [aceriverson/titles.run#6]
My primary language is JS... There's a mix of camelCase and snake_case, we should adhere to Python's standards and move all to snake_case.

**Comment by ilhamday** [comment]
Hi, I think I can work on this. 
I'll follow [Function and Variable Names](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names) guide. And how do I contribute to your repo?

**Comment by aceriverson** [comment]
@ilhamday 

Thank you for your interest in contributing to the project! The python.org guide is what I am looking for. Primarily replacing camelCase variables and functions with snake_case.

> And how do I contribute to your repo?

I apologize for not having a contribution guide yet. Maybe I'll put an issue up for that.
[This tutorial](https://www.dataschool.io/how-to-contribute-on-github/) should help for a first contribution if you need it.

Thanks again!

**Comment by ilhamday** [comment]
Ok, I'll look into the tutorial. Can you assign it to me?

**Comment by aceriverson** [comment]
Thanks for the good work. Closing this issue with [PR](https://github.com/aceriverson/titles.run/pull/8#issue-546416795)
